### ISSUE TITLE
App does not report bluetooth is turned off

### ISSUE THREAD

**Issue by wolfc01** [minvws/nl-covid19-notification-app-android#21]
After install of app, 1.0.0 (68251-1e56b23) and accepting all questions, the app reports to be operational. I closed the app and left phone for a few hours .  Then I turned off the Bluetooth of my phone. The app does not ask me to turn it on again, even for 24 hours of bluetooth turned off.

I live in Utrecht. Phone: galaxy tab s7 (SM-G930F) Android 8.0.0

Br
Carl.

**Comment by hvisser** [comment]
What happens on phones is that you should get a notification from the system to tell you bluetooth is off. This notification is generated from Google Play Services. If you have turned off these notifications in the past, nothing will be shown. If you open the app without bluetooth enabled, it should show you that the app is not active. Only if you turn of exposure notifications the app will notify you after a while.

Also we haven't tested extensively on tablets, since the primary use case is phones.

**Comment by wolfc01** [comment]
Hi Hvisser,  

Thanks for answering. I really like to help :-) 

I reported my phone type wrong: it is a samsung galaxy S7, not a tab S7, so sorry for that.

Can you give the steps I have to do in order to test the handling of the app in the situation where BT is turned of manually? I think turning off BT and location services (as far as i know bt and location service have to be turned on to use ble) is an habit of many phone users in order to save battery.

**Comment by hvisser** [comment]
Thanks for that correction, if you have enabled the app, and settings -> Google shows that "Blootstellingsmeldingen" is enabled, then toggling bluetooth off should show a notification. This is generated from Play Services. If you are not seeing that you might have disabled notifications for Play Services in the past, you can check that from Settings -> app and looking for Google Play Services to get more info.

If you do the same with the app open on the status screen, it should change and tell you the app is inactive.

re: battery and bluetooth/location, that's mostly a myth. BLE hardly uses any power and location only uses power if you use GPS and if an app is actively using it. It should be fine to keep both on, unless you have some really misbehaving apps installed.

**Comment by wolfc01** [comment]
Hi Hvisser,

thanks for the info it works now.  So there is a usecase which leaves the app "not working" unnoticed:
* Turn of notifications for play services
* Install the app, go to the screens "app aanzetten"such that the app reports "the app is actief". 
* Then turn off BT a bit later
--> app is not working unnoticed.

Is it an idea when the app is in the background "app sluit" to check periodically if everything is in place and give a notification, without relying on the play services notifications to be turned on?

In my family I had already 2 cases which have had the above use case. So 50% of my family has the app installed but the app does not work, unnoticed.

> battery and bluetooth/location, that's mostly a myth
I agree and true, but it still may be a significant risk regarding the above use case, leaving too many users which a non working app, unnoticed.

I am a kind of user which do not like rings and bells going off all the time on my phone so I carefully switched off a lot of those rings and bells, causing the above use case and problem.

Anyway I'm interested if the above use case is important enough to give it a follow up.

Br
Carl

**Comment by hvisser** [comment]
For now the solution is not to turn off those Play Services notifications for this exact reason. In general it's best to keep Play Services settings to their defaults, as it might affect all apps that are using Play Services, not just CoronaMelder.

Checking this periodically we could do, but for users with the notifications turned on that would result in multiple notifications, which we rather not have either. But I'll flag this as a feature so that we can track it for future development.

**Comment by wolfc01** [comment]
HI Hvisser,

I fully agree. As a extra refinement: check the playservices notifications once at app install time, and explain the user what to do when this setting is turned off.

Br Carl.

**Comment by hvisser** [comment]
We filed a feature request with Google for this, but it's unlikely that this going to be implemented, which unfortunately means that we are unable to check/act when Play Services notifications have been disabled for some reason. I'm going to close this issue for that reason.
