### ISSUE TITLE
[2020-08-20]: [VWS/Covid19NotificationApp] Background sync issue

### ISSUE THREAD

**Issue by sezijlema** [minvws/nl-covid19-notification-app-android#23]
### Describe the bug, issue or concern

When I haven't opened the app in more than a day and then open it, I get the error "The app couldn't connect to the internet for the past 24 hours. Check if your Wi-Fi or mobile data is turned on.", i.e. the sync_issue_notification_message. When the app cannot sync the codes, notifications will not work.

- Bluetooth, Wi-Fi and mobile data have been on all day, except at night.
- I do receive the "Exposure notifications inactive " notification from Google Play Services when I disable Bluetooth.
- Installation went smoothly and the app states "This app is active". Even when I got the sync_issue_notification_message, the app still stated "This app is active".

### To Reproduce
Do not use app for >24 hours and open app.

### Expected behavior
Background sync to allow for notifications.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9 Lite
 - OS: Android 10
 - MIUI version: 11.0.3

### Additional context
I think the aggressive background app killing functionality of MIUI may kill the Coronamelder app in the background, but similar issues [may arise](https://dontkillmyapp.com/) on phones from certain other manufacturers. There are ways to allow the app to run in the background, but this requires [following many steps](https://dontkillmyapp.com/xiaomi), which many users will not (know how to) do.

I have now followed these steps and background sync should work for me now.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
Thanks for the report, we are investigating this. OEM custom battery saver apps are the most likely cause indeed. Can you check if you have an exposure check in the Google settings? There's should be one check currently. If there is, could you also mention the date / time of that check? That will give an idea of how much the battery saving is affecting.

If you would be able to test with both default battery saving settings on your Xiaomi phone and with specific settings (custom to Xiaomi) disabled, assuming they provide it, that would also be greatly appreciated.

**Comment by sezijlema** [comment]
The Google settings state "0 checks in the past 14 days", but I've only installed the app on 17-08.

I'd be happy with testing the battery saving settings and their impact on the app. Just let me know which settings you want me to try.

**Comment by hvisser** [comment]
OK, the 0 checks indicated that it was not running in the background at all, so that's not good. If you open the app again to ensure it schedules the check correctly you should see a check later, it could take up to 4 hours.

Thanks for specifying the settings here! I'm not sure there's a technical way to resolve it, more testing is needed for that. Otherwise we might need to guide users through these settings somehow, but that's to be determined.

**Comment by jjt00** [comment]
I happen to use a Xiaomi Mi 9 lite as well, which is why I also got concerns about the background functionality. However, the app does work for me after changing the MIUI settings. I've got 3 checks from the last couple days. Difference might be that I usually try to disable as many Xiaomi/Mi/MIUI settings, bloatware and applications I can.

**Comment by hvisser** [comment]
Thanks for the additional info. This is our top priority currently and we are investigating if we can make technical changes or if a user really needs to change the settings to make this work. There are two scenarios which we are looking into:

* People seeing "no internet" notifications posted -- this indicates the app is brought back to life by ENS on the device, though no checks are happening.
* People _not_ seeing that notification, but only seeing that status in the app -- this could indicate the app is not brought back to life ever which would mean a possible solution would be to somehow explain in the app to disable these excessive battery management apps for specific devices.

**Comment by hvisser** [comment]
The exposure check is only updated when there are new reported cases, so in that sense it's not a good indicator to see if the app is working unfortunately. The delay you are seeing from opening the app until the first check is expected behaviour, though we might remove it for the next update. 

These phones usually also retain the stock battery optimisation settings. On MUI this is under  Passwords & Security -> Privacy -> Special app access -> Battery optimization (!!!). One of the things we're investigating if setting CoronaMelder to "not optimized" will make sure the background processing keeps running correctly.

**Comment by TheLastProject** [comment]
This was posted on Tweakers, which is how I found this issue: https://tweakers.net/nieuws/171338/nederlandse-corona-app-werkt-niet-goed-op-achtergrond-door-accubesparingsmodus.html. I sadly can't use the app due to a lack of support for microG and thus can't help test, but I was hoping my two cents may possibly contain an usable suggestion in solving this anyway.

I would like to suggest considering researching using a foreground service. This requires showing a notification at all time (which I know is not pretty UI), but if you can't get your desired results with disabling battery optimizations and have trouble explaining to users how to disable it, it may be a good fallback.

Here's a bit of code that shows how creating a foreground service works, just in case you weren't aware: https://github.com/TheLastProject/RaiseToAnswer/blob/0094ac3f4cf46b99ba2ff45870f0d235a9f833df/app/src/main/java/me/hackerchick/raisetoanswer/RaiseToAnswerSensorEventListener.kt#L75-L85

**Comment by roelofr** [comment]
As this issue is gathering wind (I noticed it on Tweakers), I decided to look into how my phone is handling it now that I've been using it for about two weeks (I'm in Overijssel).

When I opened the app I did briefly see a "no connection in 24 hours", but after further investigation in the Android settings, noticed the app had only accessed the IDs twice. Once on August 19th (sending 150 keys) and once just now when I checked the app (sending 2550 keys).

I'm using a OnePlus 5 (OxygenOS 10.0.0.0, Android 10) and it's aggressive battery optimisation tactics are really showing here. I've disabled "intelligent battery control" for now to see if it helps.

**Comment by sezijlema** [comment]
The Xiaomi settings that I use seem to work well. I now have 13 checks since 22-08 and I have not seen the "24h no connection" message anymore. 

> These phones usually also retain the stock battery optimisation settings. On MUI this is under Passwords & Security -> Privacy -> Special app access -> Battery optimization (!!!). One of the things we're investigating if setting CoronaMelder to "not optimized" will make sure the background processing keeps running correctly.

I will reset my battery optimization settings to default and give this option a try. 
By the way, [this app](https://play.google.com/store/apps/details?id=com.ceyhan.sets) is able to directly open this menu by clicking _Battery Optimization_, so such a shortcut is possible and would save MIUI users a lot of clicks.

**Comment by krulkrul** [comment]
Can confirm the issue on Xiaomi MI 9 SE with MIUI version 12.0.1 (global). I get the same 'couldn't connect to the internet' message and Google settings says: 0 checks in the past 14 days. After installing i have not touch the battery saver setting, it apparently defaulted to 'MIUI Batttery saver'. I can change the setting to 'No restrictions' if that would help debugging.

**Comment by roelofr** [comment]
I've ran a test after my [initial comment][1] with disabling the "Adaptive battery" feature on my OnePlus, but it had no effect and the app still gave the notification _after_ I opened the app (and then requested 600 keys from the API).

Turning off the optimisation seems to be the only solution for OnePlus for now.

[1]: https://github.com/minvws/nl-covid19-notification-app-android/issues/23#issuecomment-684090295

**Comment by sezijlema** [comment]
> These phones usually also retain the stock battery optimisation settings. On MUI this is under Passwords & Security -> Privacy -> Special app access -> Battery optimization (!!!). One of the things we're investigating if setting CoronaMelder to "not optimized" will make sure the background processing keeps running correctly.

I just found out that apps are automatically changed to "not optimized" in the list mentioned by @hvisser when you change the "Battery saver"setting in app settings to "No restrictions":
<img src="https://user-images.githubusercontent.com/43772089/91978225-111de980-ed24-11ea-9abd-06c1222e3649.png" width="400">

You may have to close the Settings app from your Recently opened apps to refresh the Battery optimization list after you change this setting, but then the app is added there automatically. The other way around does not work: changing to "not optimized" under Special app access -> Battery optimization does not change the Battery saver setting in app settings.

Another question to test would be: is it necessary to enable the "Autostart" option?

**Comment by hvisser** [comment]
Yes, I'm pretty sure that auto start has to be on and set to manual and I would recommend to enable all options there (though the middle one that allows starting the app from "other apps" is probably the important one).

**Comment by michaelw85** [comment]
I'm using a Xiaomi MI9 and I can confirm this issue.
I can also confirm that after enabling autostart and disabling battery saver my checks went from 0 in 14 days to 2 after a couple of hours. So this seems to fix the issue.

**Comment by krulkrul** [comment]
For me the Coronamelder app is now synchronizing with autostart is disabled and no restrictions for battery saver. Last check was yesterday evening and i am sure i have not opened the corona app at that time, so it was triggered in the background.
I am using Xiaomi MI 9 SE with MIUI version 12.0.1 (global)

**Comment by roelofr** [comment]
I've been running all across Europe with the app, and it hasn't gotten severely out of sync at all, so I guess it's been resolved pretty robustly.
