### ISSUE TITLE
Cannot install - "Your play services is out of date" - UnifiedNlp (no GAPPS)

### ISSUE THREAD

**Issue by flatsiedatsie** [minvws/nl-covid19-notification-app-android#34]
### Describe the bug, issue or concern

After intalling I get the message "your Google Play Servies is out of date". There is an "update" button. Clicking it shows "UnifiedNlp (No GAPPS) in F-droid, without any possibility to update it.

A bigger question is: why does the app need access to a location service? Wasn't the whole point that it didn't use that stuff?

### To Reproduce
1. Take a normal up-to-date Galaxy S7 (no custom rom)
2. Install F-droid and make it the default app store
3. Use phone for a few years with as privacy frendly apps as possible
4. Install Coronamelder
5. Open Coronamelder

### Expected behavior
See above.

### Screenshots

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - Device: Galazy S7 SM-930F
 - OS: android 8
 - Play services: 17.4.55
 - Browser Not relevant
 - Version Not relevant

**Comment by hvisser** [comment]
The app uses BLE scanning and all apps that use this need to have location services enabled, since you could use BLE scans to determine location. CoronaMelder does not use your location as it doesn't request or uses the location permission (these are two separate things). 

Only on the recently released Android 11 version the requirement for location services and BLE scanning has been lifted for apps that use the exposure notification framework.

The requirement for location services and BLE scanning is a OS-level requirement which is there regardless of using a phone with Google apps or not. This requirement is for all apps that use this technique.

As for supporting f-droid or phones without Google Play Service or alternative versions of Google Play Services: the app currently requires Google Play Services for the Exposure Notification Service implementation and we currently don't support other implementations. Some users have reported the app to work with microG, which might be an option to try. However we haven't validated that the microG implementation has the exact same behaviour compared to the Google Play Services implementation so even while CoronaMelder might work, it might still be less reliable. Again, it's not something we can support.

I hope this clarifies your question around the requirement of location services (not location permission / actual location) and using the app on non-Google experience phones. I'll go ahead and close this issue but feel free to leave additional comments if you have any further questions.

**Comment by flatsiedatsie** [comment]
Out of curiosity: what is the percentage of Android phones that have a recent enough version of play services installed?

**Comment by hvisser** [comment]
I don't know the percentage, but it should be the majority of Android phones. CoronaMelder supports Android 6 and up and play services is updated at regular intervals on all these phones (for various types of functionality including exposure notifications).

**Comment by hvisser** [comment]
> Thank you for the clarification. I must have fiddled with MicroG some time in the past. I guess this aspect being "broken" has been a feature for me.

It's not broken persé, it's an alternative implementation. Personally it's great that this choice is possible on Android. What I meant to say though is that in the case of exposure notifications it's important that the alternative implementation behaves the same as the original, so ideally that would be validated. If something is broken or different that might affect you or your health, so it's a bit of a different case compared to other features that microG or other alternatives offer IMHO.
