### ISSUE TITLE
20200808: Inclusion criteria for F-Droid app store

### ISSUE THREAD

**Issue by PanderMusubi** [minvws/nl-covid19-notification-app-android#9]
### Describe the bug, issue or concern

Investigate if the app can meet the inclusion criteria to be build, distributed and installed via the F-Droid app store, see https://gitlab.com/fdroid/rfp/-/issues/1441 For starters, see the question on the Exposure API.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
As it stands currently this app builds upon the GAEN protocol which I do know any alternative implementations for. The Google/Android implementation is delivered through Google Play Services + the sdk that is included as a binary which as pointed out in [this comment](https://gitlab.com/fdroid/rfp/-/issues/1441#note_391143911) is a show stopper for F-Droid inclusion. So as far as investigating the possibilities, this currently seems to be a dead end I'm afraid.

**Comment by PanderMusubi** [comment]
Thanks for your reply. Perhaps when that part is under review or in other new apps, publication on F-Droid is taken into account.

**Comment by peternowee** [comment]
> As it stands currently this app builds upon the GAEN protocol which I do know any alternative implementations for.

Maybe this one from MicroG?
https://github.com/microg/android_packages_apps_GmsCore/issues/1057

**Comment by peternowee** [comment]
Could you please reopen this issue until it is really solved, by the way?

**Comment by nielsvm** [comment]
> So as far as I understand the availability of a microG implementation for the proprietary ExposureNotification API does not help in making it eligible for F-Droid. I'd be interested to learn if I'm not understanding this correctly, of course ;).

Correct, apps in F-Droid can't adopt any feature exposed by GooglePlayServices. While a laudable solution for some, *microG* only re-implements and replaces core functionalities provided by GooglePlayServices, for instance for people who otherwise cannot use their bank app. Its basically replacing a "blackbox" in your phone with a more understood-replacement, which tries to avoid depending on Google servers, but in the case of the GAEN-substitute, it must still communicate with Google servers.

> Ok, so it seems we need to distinguish the Exposure Notification API service (which microG is also trying to offer now) from the API client library. Supposedly, that second part is not open source right now. Correct?

I can clarify best using bullets:
- The GAEN **webservices** offered by Google/Apple are entirely closed and can't be audited, neither can the security practices and GDPR-compliance be audited here. This is also the core concern of the [Autoriteit Persoonsgegevens](https://www.tweedekamer.nl/downloads/document?id=cf8da4cd-0f7d-4cf3-aade-a2c9b9dfb98b&title=Advies%20Autoriteit%20Persoonsgegevens%20%28AP%29%20op%20voorafgaande%20raadpleging%20COVID19%20notificatie-app.pdf#page=8).
- **GooglePlayServices**, ships the GAEN client library and is closed and can't be audited.
- The **microG** drop-in replacement is open source and can be audited, but the servers it talks to (at Google/Apple) cannot.

**Comment by peternowee** [comment]
Hmm, bad news. So it seems that the app would need to switch to a different protocol/framework, which would mean going back to the drawing board for important parts of it, or maybe add support for additional protocols/frameworks besides GAEN, right? (Some alternative frameworks/protocols mentioned in https://github.com/minvws/nl-covid19-notification-app-coordination/issues/67.)

**Comment by ljl-covid** [comment]
There is also [CoraLibre](https://github.com/CoraLibre/CoraLibre-android-sdk) that aims to produce an open source exposure notification library. The approach is different from microG in that it is not meant to let apps run unchanged with their proprietary client library in the binary, but instead, to build a version of the app that makes use of CoraLibre instead of the Google exposure notification API.

That would qualify for inclusion in F-Droid, and in fact, it's the entire reason the project was started: to make the German [Corona-Warn-App open enough to satisfy the inclusion criteria](https://github.com/corona-warn-app/cwa-app-android/issues/75).

**Comment by rugk** [comment]
For more arguments regarding why an F-Droid release (even if that would only be possible in a self-hosted F-Droid repository) see https://github.com/corona-warn-app/cwa-app-android/issues/1483 for the German covid warn app.

**Comment by PanderMusubi** [comment]
See also progress at https://gitlab.com/fdroid/rfp/-/issues/1387

**Comment by FintasticMan** [comment]
I have just noticed this issue, and I did some digging. I found this app, which is a patched version of CWA that either uses the microG that is already installed, or if that isn't available, it uses a bundled implementation of the microG Exposure Notifications: [https://f-droid.org/en/packages/de.corona.tracing/](https://f-droid.org/en/packages/de.corona.tracing/). It has been approved for inclusion on the official F-Droid repository, so if it's possible to patch CoronaMelder in a similar way, it could also be included. The source code can be found here: [https://codeberg.org/corona-contact-tracing-germany/cwa-android/](https://codeberg.org/corona-contact-tracing-germany/cwa-android/).
I don't know very much about developing android apps, but I hope that this helps.

**Comment by matthijskooijman** [comment]
Adding a little detail to what @FintasticMan said, it seems that the version of CWA in F-Droid is a *fork* of CWA that can be found here: https://codeberg.org/corona-contact-tracing-germany/cwa-android (They refer to the fork as CCTG, Corona Contact Tracing Germany). 

The approach they use to support microg seems to be recommended and supported by the microg author, which has made the EN part of microg available to be used as a library directly. I noticed instructions on implementing this [here](https://github.com/corona-warn-app/cwa-app-android/issues/1483#issuecomment-733961970), I presume that CCTG did pretty much that (maybe more, git diff will likely help here). I also looked for some official docs at microg, but only found this issue about this feature, so I asked there: https://github.com/microg/GmsCore/issues/1166

**Comment by FintasticMan** [comment]
Thanks for the additions!

The people behind CCTG have [said](https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/1#issuecomment-159453) that they all they have really done is replace Google's API with microG's, and changed the name and icon. I did a diff between tag `v1.7.1` of CWA and tag `v1.7.1.2` of CCTG, which can be found [here](https://pastebin.pl/view/a3551718). It is quite long, and I don't have enough time to figure out what everything does. Maybe someone else who is more experienced than me could take a look at it and see how much would be possible to use in CoronaMelder?
